script:
  - 'if [ -n "${BUILD-}" ]; then npm run build-master; fi'
  - 'if [ -n "${BUILD-}" ] && [ "${TRAVIS_BRANCH-}" = "master" ]; then ./scripts/auto-deploy.sh; fi;'

env:
  global:
    - secure: "UCSm2OZkCtH8EPSPjp8fujOyQrtHtPJi8DDdOyCSkUunSw9H+HiONwuh+J1Of77B9OUC1HTWE51tW75nsnaQik4GihXB+eah7ow3RLM14LoLoUz+PA84W8sDuuCbm37Kqtf4vnWKlAUhDeUZNyhGyIezdB22UaqWWir9KGdp4AE="

matrix:
  include:
    - node_js: "lts/*"
      env: BUILD=true

language: node_js

sudo: false
