name: 'ecma-262'

on: [pull_request, push]

jobs:
  build:
    name: 'build & lint ecmarkup'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/install@56f291b2a0d9e3bce72634356ae949b1e054b9f8
        name: 'nvm install lts/* && npm ci'
        with:
          node-version: lts/*
          use-npm-ci: true
      - run: npm run build-master
