name: 'ecma-262'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'deploy github pages'
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'tc39/ecma262' }}

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/install@56f291b2a0d9e3bce72634356ae949b1e054b9f8
        name: 'nvm install lts/* && npm ci'
        with:
          node-version: lts/*
          use-npm-ci: true
      - run: npm run build-only
      - run: ./scripts/auto-deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
