name: 'ecma-262'

on:
  pull_request_target:
    branches:
       - '*'
  push:
    branches:
       - main

jobs:
  build:
    name: 'check IPR form'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/install@56f291b2a0d9e3bce72634356ae949b1e054b9f8
        name: 'nvm install lts/* && npm ci'
        with:
          node-version: lts/*
          use-npm-ci: true
      - run: 'npm run ipr-check'
        env:
          GH_TOKEN: ${{ secrets.GH_IPR_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
