name: Build Preview

on: [pull_request]

jobs:
  build:
    name: 'build PR preview'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/install@56f291b2a0d9e3bce72634356ae949b1e054b9f8
        name: 'nvm install lts/* && npm ci'
        with:
          node-version: lts/*
          use-npm-ci: true
      - run: npm run build-only
      - run: node scripts/insert_snapshot_warning
      - run: echo ${{ github.event.number }} > out/pr.txt
      - uses: actions/upload-artifact@v2
        with:
          name: out
          path: out/
